[SYS_CNTRL_PARA]
#0~1 1:cad_data;0:scene_data;
is_cad=0
#1~4 LEICA_TYPE_0 = 1,LEICA_TYPE_1 = 2,INDUSTRY_TYPE_0 = 3,INDUSTRY_TYPE_1 = 4 
scanner_type=1

[LINE_CNTRL_PARA]
#0~1 point density is auto detected else fixed value is set;
is_point_density_set=1
#point density for normalEstimation, invalid while is_point_density_set is false
point_density=15
#0~1 0:represents all the config value of SEG_THRSHLD_CONFIG  are invvalid, 1 represents they are valid
line_thrshld_section_valid=1

[PXL_SIZE_CONFIG]
length_x_of_pixel=60.0
length_y_of_pixel=60.0

[LINE_THRSHLD_CONFIG]
#define neighbor in_line_flag
min_line_dist_2pixel=10

#good neighbour(neighbor_flag)
max_normal_angle_of_2pixel=20
#邻居center 到 直线距离小于min_line_dist_2pixel 且 夹角小于max_normal_angle_of_2pixel, 则in_line_flag为true, 判断邻居与此pixel是否在一条直线?

#defile in_line_pixel
max_mse_of_line=20

#define high weighted mse?
#point mse超过此值为high weighted mse.
min_line_dist_pt2pixel=10

#define good pixel
max_mse_of_pixel=20
max_high_mse_ratio=0.10
min_point_num_of_line_pixel=2
#pixel mse 小于 max_mse_of_pixel, high mse ratio 小于 max_high_mse_ratio 且 point size 大于 min_point_num_of_line_pixel 则为good pixel?

#define line min point and pixel?
#why use in MergeGoodPixels?
min_point_num_of_line=4
min_pixel_num_of_line=2

#merge line (check same line condition)
min_dist_of_2line=5
max_angle_of_2line=10


[LINE_DBG_PARA]
#0~1 0:represents all the flowing value of LINE_DBG_PARA  are invvalid, 1 represents they are valid
dbg_section_valid=1
#0~10 reserved test parameters
reserved_test=2
#0~1 output missing_points.txt file and missing_points_info.txt file
missing_point_output=0
#0~1 output pixel_neighbour.txt file for voxel neighbour debug info
neighbour_info_debug=0
#0~1 output line_output.txt file for plane output debug info
line_output_debug=0
#0~10 reserved test1 parameters
reserved_test1=1
