[SYS_CNTRL_PARA]
#0~1 1:cad_data;0:scene_data;
is_cad=0
#1~4 LEICA_TYPE_0 = 1,UNRE_TYPE_0 = 2,INDUSTRY_TYPE_0 = 3,INDUSTRY_TYPE_1 = 4 
scanner_type=2
#0 plain; 1 UNRE_ENCRYPTION
encryption_type=1

[VOXEL_SIZE_CONFIG]
#invalid  while voxel_size_detected_type is 1
voxel_x_length=80
voxel_y_length=80
voxel_z_length=80

[SYS_DBG_PARA]
# detc2D new method =1 , old = 0
reserved_int0=0
reserved_int1=0
#pixel size ratio to voxel size
reserved_float0=0.2
#sigma ratio 
reserved_float1=2.0  

[FILTER_CNTRL_PARA]
#1~3 1:no downsample 2: downsample and output with points after downsample 3: downsample and output with orignal points
downsample_type=3
#float, recommend around the value of (length_x_voxel+length_y_voxel+length_z_voxel)/3/15; if leaf size is zero ,  no downsample
downsample_leaf_size=15.0
#0~1 0:no input data filtering  1: have input data filtering
is_input_filtered=1
#0~1 0:no unit check 1: have unit check, default unit is mm
is_input_unit_check=1
#0~1 1:represents axis space is selected with the cloud center otherwise is same as origin axis space
origin_in_cloud_center=0

[NORMALEST_CNTRL_PARA]
#0~1 0: fixed value else 1 : auto detected; 
is_voxel_size_detected=0
#0~1 point density is auto detected else fixed value is set;
is_point_density_set=1
#point density for normalEstimation, invalid while is_point_density_set is false
point_density=15

[NORMALEST_THRSHLD_CFG]
#3~max if points number of voxel < value, voxel is regard as bad voxel,must same as  min_point_num_of_flat_voxel in SEG_THRSHLD_CONFIG
min_point_num_of_valid_normal_voxel=10
#0~90 normal difference threshold of two voxels who are the good neighbours, must same as in SEG_THRSHLD_CONFIG_DEBUG
max_normal_angle_of_2voxel=10
#0.0~1.0, max mse ratio to voxel size, if mse ratio > value, not a flat voxel, must same as in SEG_THRSHLD_CONFIG
max_mse_ratio_of_voxel=0.3


[SEG_CNTRL_PARA]
#0~1 1:identify with  bridge voxel
identify_with_bridge=0
# segmenting planes  filtering strategy, 0: no filter 1: Only good voxel 2: no normalEstimation if(8~9),with multiplane points
filtering_strtgy_type=8
#0~2 0: using default config 1:value of SEG_THRSHLD_CONFIG  are invalid, 2 value of SEG_THRSHLD_CONFIG_DEBUG are invalid
seg_thrshld_section_valid=2

[SEG_THRSHLD_CONFIG]
#0~max,  if voxels of a plane < value, plane is ignored
min_voxel_num_of_plane=5
#0~max, if points of a plane < value, plane is ignored
min_point_num_of_plane=2000
# >0.0~1.0, voxel max mse ratio to voxel size, if mse ratio > value, voxel is regarded as bad voxel
max_mse_ratio_of_voxel=0.3125
# >0.0~1.0, max mse ratio to voxel size, if mse ratio > value, plane is ignored
max_mse_ratio_of_plane=0.125
# 0~max, if points number of voxel < value, voxel is regard as bad voxel
min_point_num_of_flat_voxel=10
#0~1 distance ratio to voxel size, distance ratio of same planes must < threshold
min_dist_ratio_of_2plane=0.25
#0~1 distance ratio to voxel size, if points cloud closed distance < threshold, 2 planes are regarded as connected planes
max_dist_ratio_of_connected=0.35

[SEG_THRSHLD_CONFIG_DEBUG]
min_plane_dist_of_2voxel=30
min_dist_of_point2voxel=35
max_normal_angle_of_2voxel=10
max_mse_of_voxel=32
min_point_num_of_plane=2000
#if less, will get more points from neighbor while compute normal 
min_voxel_num_of_plane=5
max_mse_of_plane=12.0
#if less,voxel is regard as bad voxel
min_point_num_of_voxel=10
min_plane_dist_of_2plane=26
max_normal_angle_of_2plane=9
max_normal_angle_of_edge_point=45
max_high_mse_ratio=0.01
min_good_group_in_plane=5
#if less,voxel is regard as tiny voxel
min_point_num_of_flat_voxel=10
max_dist_of_2voxel_connected=45
#if less, the plane normal is not accurate 
min_good_plane_voxel_size=50


[SEG_DEBUG_CONFIG]
#0~1 0:represents all the flowing value of KEY_DEBUG_INT  are invvalid, 1 represents they are valid
dbg_section_valid=1
#0~10 reserved test parameters
reserved_test=1
#0~1 output missing_points.txt file and missing_points_info.txt file
missing_point_output=1
#0~1 
io_debug_info=0
#0~1 output good,pseudobad,extend or edge points debug info
voxel_info_debug=0
#0~1 output voxel_neighbour.txt file for voxel neighbour debug info
neighbour_info_debug=0
#0~1 if 1 will output planes without plane mering otherwise zero
no_plane_merge=0
#0~1 output plane_output.txt file for plane output debug info
plane_output_debug=1
#0~1 output merge_pseudobad_output.txt file for good voxel merge debug info
merge_pseudobad_voxel_debug=0
#0~1 output debug file for real bad voxels merge
merge_bad_voxel_debug=0
#0~1 debug get lost plane info in process of merging pseduo bad  plane
pseudo_bad_lost_plane_output_debug=0
#0~1 if 1 will output plane xyz after downsample ,otherwise zero
is_dwnsmpl_output=1
#0~1 output points_group_neighbour.txt file for group merge debug info
points_group_neighbor_output_debug=0
#0~1 merge same plane debug info ouput
merge_same_plane_output_debug=1
#0~1 debug get result of normal estimation module by saved file before
include_get_nm_by_file=0
#0~1 debug info for output result of normalEstimation
nm_file_ouput_debug=0


