#ifndef _DETC_EDGE2D_H_
#define _DETC_EDGE2D_H_
#include "detc_macro.h"
#include "detc_edge.h"
//#include "DataStruct.h"
#include "../../../CutScanPlane/models/voxel2d.h"
#include "ModuleStruct.hpp"


/**
* \brief class for detect edge in 2D plane
*
* operation will export/return data outside for other purpose
* operation member pointers point to outside model cannot be modified within class functions
* operation member data will be destroyed when renew the operation
*
*/
class DW_Detc_Edge2D {
public:
	/**
	* \brief constructor
	*/
	DW_Detc_Edge2D();
	/**
	* \brief constructor with input point-set and normal
	* @param ptArray point-set of plane-shaped
	* @param nPlane estimated normal vector of fitted plane of point-set
	*/
	DW_Detc_Edge2D(ModuleStruct::Point3fArray* ptArray, const ModuleStruct::Point3f nPlane, const double voxel_length);
	/**
	* \brief destructor
	*/
	~DW_Detc_Edge2D();
	/**
	* \brief initialize voxelgrid for detection
	* 
	* initialize and detect are separated, initialize is to
	* generate voxelgrid based on projected plane, detect is to
	* find edges on voxelgrid with variant parameters, e.g. threshold
	*
	* initialized data can be used for multiple edge detection methods
	* 
	* @return if class member are initialized or not
	*/
	bool init();
	/**
	* \brief clear
	*
	* reset pointer of point array and normal
	* must not clear point array inner data
	* clear assistant members
	*/
	void clear();
	/**
	* \brief detect via coarse contour
	*/
	bool detect();
	bool detect_bn();

	/**
	* \brief set point-set
	* 
	* detector set function has no authority to clear point array data
	*/
	void setPtArray(ModuleStruct::Point3fArray* ptArray);
	/**
	* \brief set plane normal
	*/
	void setNPlane(const ModuleStruct::Point3f nPlane);
	/**
	* \brief get point-set
	*/
	ModuleStruct::Point3fArray* getPtArray();
	/**
	* \brief get plane normal
	*/
	ModuleStruct::Point3f getNPlane();
	/**
	* \brief get voxelgrid
	*/
	VoxelGrid2D* getVoxelGrid();
	/**
	* \brief get image of voxelgrid
	*/
	ModuleStruct::CMat getImgVoxelGrid();

	/**
	* \brief initialize image of voxelgrid
	*/
	bool initImgVoxelGrid(unsigned int row, unsigned int col);

	/**
	* \brief get contours of voxelgrid
	*/
	ModuleStruct::Vector<ModuleStruct::Point2iArray> getContours();

	/**
	* \brief set voxel size of voxelgrid
	*/
	bool setVoxelSize(double voxel_length);

	/**
	* \brief get voxel size of voxelgrid
	*/
	double getVoxelSize();

	/**
	* \brief set output path (for debug information)
	*/
	inline void setOutputPath(std::string path)
	{
		output_path = path;
	}

	/**
	* \brief get output path (for debug information)
	*/
	inline std::string getOutputPath()
	{
		return output_path;
	}

	/**
	* \brief get orginal map  in 3D space of 2D contours
	*/
	bool getOrigMapOfContours(ModuleStruct::Vector<ModuleStruct::Point3fArray> &orig_map);

	/**
	* \brief get orginal map  in 3D space of 2D contours
	*/
	bool getOrigMapOfContours(ModuleStruct::Point3fArray& orig_map);

	/**
	* \brief get contours  in 2D space
	*/
	bool get2DContours(ModuleStruct::Vector<ModuleStruct::Point2fArray> &contours);
	bool get2DContours_bn(ModuleStruct::Point2fArray& contours);

	/**
	* \brief get contours  in 2D space
	*/
	void setPointsCenter(ModuleStruct::Point3f center)
	{
		m_center = center;
		data_center_input = true;
	}

private:
	/**
	* \brief clear voxel grid
	*
	* m_voxelgrid is internal member generated by m_ptArray and m_nPlane
	* internal clear function should not be access from outside
	*/
	void clearVoxelGrid();
	/**
	* \brief clear contours vector
	*/
	void clearContours();
	/**
	* \brief detect contour in image by findcontours
	*/
	void detect_img_cnt();
	/**
	* \brief detect edge in image by Canny
	*/
	void detect_img_edge();
	/**
	* \brief detect edge via Canny threshold
	*/
	void detect_img_edge_Canny(ModuleStruct::CMat src_gray,
		ModuleStruct::CMat detected_edges, int lowThreshold, int ratio,
		int kernel_size, ModuleStruct::CMat dst, ModuleStruct::CMat src);

	/**
	* \brief detect exact edge pts in projected plane by intenstity
	* \actually intensity is not reliable because it highly depends on voxel position in edging area
	*/
	void detect_pt_edge_by_intensity();
	/**
	* \brief detect exact edge pts in projected plane by studying neighbor voxels
	*/
	void detect_pt_edge_by_neighbor_voxels();
	/**
	* \brief collect all point idx in egde voxels & the neighbor point idx 
	*/
	void collect_edge_pts_and_neighbor_pts(Voxel2D** voxels,
		const std::vector<std::pair<unsigned int, unsigned int>>& edge_voxel_idx, /*voxel idx having edge points*/
		const std::vector<std::pair<int, int>>& neighbor_voxel_idx_offsets, /*voxel idx offset of neighbor voxels relative to edge voxel*/
		std::vector<std::vector<unsigned int>>& pts_in_edge_voxels, /*pts in multiple edge voxels*/
		std::vector<std::vector<unsigned int>>& pts_in_edge_voxels_neighbors /*pts in all neighbors of multiple edge voxels*/);
	/**
	* \brief detect edge pts & store in global edge_pts;
	*/
	void find_edge_pts_by_bilateral_kernal(const std::vector<std::vector<unsigned int>>& pts_in_edge_voxels, /*edge pts*/
		const std::vector<std::vector<unsigned int>>& pts_in_edge_voxels_neighbors, /*neihbor pts*/
		const float kernal_half_length, /*using stripe kernal, kernal length (long side)*/
		const float kernal_half_height /*using stripe kernal, kernal height (short side)*/);

	/**
	* \brief  debug for showing voxel neighbor index
	* @param [in] voxel_idx, voxel index of occupied voxels
	*/
	inline void getVoxelPts(std::vector<std::vector<unsigned int>> pts_in_voxels, const char* file, int line)
	{
		log_log(LOG_DEBUG, file, line, " pts_in_voxels  size = %d ", pts_in_voxels.size());
		for (size_t i = 0; i < pts_in_voxels.size(); i++)
		{
			if (i > 4) continue;
			log_log(LOG_DEBUG, file, line, " voxels %d pts size  = %d ", i, pts_in_voxels[i].size());
		}
	}

#define VXL_PTS(pt_voxel) getVoxelPts(pt_voxel,__FILE__,__LINE__)


private:
	double voxel_size;///T
	ModuleStruct::Point3fArray* m_ptArray;///T		/**< point-set data */
	ModuleStruct::Point3f m_nPlane;	///T		/**< estimated normal of fitted plane of point set */
	VoxelGrid2D* m_voxelgrid;///T	/**< voxel grid of point-set */
	ModuleStruct::CMat m_img_voxelgrid; ///T	/**< image of voxelgrid, each pixel is voxel2d, used in image algorithm */
	ModuleStruct::Vector<ModuleStruct::Point2iArray> m_cnts; ///T /**< detected contours of voxelgrid */
	ModuleStruct::Point3f* m_pts;
	ModuleStruct::Point3f m_center;///T
	std::string output_path;///T
	int min_point_num_of_contour;///T
	bool data_center_input;
	float kernal_half_size; /*1st-order kernal to detect edge points in voxel, in stripe along X or Y*/
	std::vector<cv::Point3f> edge_pts_in_projected_plane; /*3D edge points in projected plane*/
	unsigned int min_pt_num_in_voxel; //threshlod for min point number in single voxel to define if edge points in the voxel
	float kernal_half_length;
	float kernal_half_height;
	unsigned int min_pt_num_in_kernal;
	float kernal_length_buffer;	
}; 


#endif // !_DECT_EDGE2D_H_
