#ifndef CONSTANT_DEFINE_H
#define CONSTANT_DEFINE_H

#define		VOXEL_FITPLANE_MIN_POINTS	20
#define		PLANE_NORMALS_CENTER_ARRAY	3
#define		VOXEL_NEIGHBOUR_SIZE	26
#define		VOXEL_NORMAL_DIFFERENCE_NEIGHBOUR_SIZE	3
#define		NORMALS_VOXEL_ANGLE_THRESHOLD 10.f
#define		COMPUTE_NORMALS_MIN_POINTS	5
#define		OCCUPIED_VOXEL_POINTS	1
#define		DENSITY_RADIUS_SCALE	1.5f

//detect voxel size
#define		DETECT_VOXEL_VALID_SIZE_RATIO	20
#define		DETECT_VOXEL_SIZE_RATIO	50
#define		DETECT_VOXEL_SIZE_STEP_RATIO	10

//detect mini radius for p2p
#define		DETECT_RADIUS_VOXEL_STEP	20
#define		DETECT_RADIUS_NEAR_POINTS	5

#define		DOWNSAMPLE_VOXEL_SIZE_RATIO	5

typedef unsigned int ns_uint32;

#endif
